// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-0ugtnXBNrpeRnl55xQtevwVSumMaEUM',
    appId: '1:620863652482:web:1b3235027b88fed724ea9b',
    messagingSenderId: '620863652482',
    projectId: 'chat-bot-app-510f4',
    authDomain: 'chat-bot-app-510f4.firebaseapp.com',
    storageBucket: 'chat-bot-app-510f4.firebasestorage.app',
    measurementId: 'G-ZJ69V2QTLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVRZ5YhTr8d8KF8cvtXDNyCFLGjGdazSY',
    appId: '1:620863652482:android:fba886812785052b24ea9b',
    messagingSenderId: '620863652482',
    projectId: 'chat-bot-app-510f4',
    storageBucket: 'chat-bot-app-510f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy02Englc3eo2YHH-vOSVEIKVcXymFIgU',
    appId: '1:620863652482:ios:f81776917093a19d24ea9b',
    messagingSenderId: '620863652482',
    projectId: 'chat-bot-app-510f4',
    storageBucket: 'chat-bot-app-510f4.firebasestorage.app',
    iosBundleId: 'com.example.chatBotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy02Englc3eo2YHH-vOSVEIKVcXymFIgU',
    appId: '1:620863652482:ios:f81776917093a19d24ea9b',
    messagingSenderId: '620863652482',
    projectId: 'chat-bot-app-510f4',
    storageBucket: 'chat-bot-app-510f4.firebasestorage.app',
    iosBundleId: 'com.example.chatBotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-0ugtnXBNrpeRnl55xQtevwVSumMaEUM',
    appId: '1:620863652482:web:3c0a0f2a4cb0537024ea9b',
    messagingSenderId: '620863652482',
    projectId: 'chat-bot-app-510f4',
    authDomain: 'chat-bot-app-510f4.firebaseapp.com',
    storageBucket: 'chat-bot-app-510f4.firebasestorage.app',
    measurementId: 'G-B7LHNXGLJ3',
  );
}
